icode: Icode-init.6 Icode-op.6 Icode-main.6
	6l -o icode Icode-init.6 Icode-op.6 Icode-io.6 Icode-main.6

robot: Icode-init.6 Icode-op.6 Icode-robot.6 Icode-robot-io.6
	6l -o robot Icode-init.6 Icode-op.6 Icode-robot.6 Icode-robot-io.6

Icode-robot.6: Icode-robot.c machine.h
	6c Icode-robot.c

Icode-init.6: Icode-init.c machine.h
	6c Icode-init.c

Icode-op.6: Icode-op.c machine.h
	6c Icode-op.c

Icode-main.6: Icode-main.c machine.h
	6c Icode-main.c

Icode-io.6: Icode-io.c machine.h
	6c Icode-io.c

Icode-robot-io.6: Icode-robot-io.c machine.h
	6c Icode-robot-io.c

clean:
	rm *.6
